### ISSUE TITLE
InceptionResnetV1: UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by deeox** [timesler/facenet-pytorch#94]
Hi! This repo is one of the best libraries to perform the task. I have been using your package for the last few weeks on a daily basis without encountering any issues. However, since the last few hours (3 July 2020 GMT+5:30), upon instantiating the resnet model with pretrained models (both, vggface2 and casia-webface) in the following way:
`resnet = InceptionResnetV1(pretrained='vggface2')` 
The following error is being generated on every run:

```
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-76-a829445a43a7> in <module>()
----> 1     resnet = InceptionResnetV1(pretrained='vggface2')

3 frames
/usr/local/lib/python3.6/dist-packages/facenet_pytorch/models/inception_resnet_v1.py in __init__(self, pretrained, classify, num_classes, dropout_prob, device)
    259 
    260         if pretrained is not None:
--> 261             load_weights(self, pretrained)
    262 
    263         if self.num_classes is not None:

/usr/local/lib/python3.6/dist-packages/facenet_pytorch/models/inception_resnet_v1.py in load_weights(mdl, name)
    334             with open(cached_file, 'wb') as f:
    335                 f.write(r.content)
--> 336         state_dict.update(torch.load(cached_file))
    337 
    338     mdl.load_state_dict(state_dict)

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    591                     return torch.jit.load(f)
    592                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 593         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    594 
    595 

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    761             "functionality.".format(type(f)))
    762 
--> 763     magic_number = pickle_module.load(f, **pickle_load_args)
    764     if magic_number != MAGIC_NUMBER:
    765         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```
My guess is that the pretrained model files were changed/corrupted. Please have a look at it.

**Comment by x13machine** [comment]
I get it error as well but only with casia-webface. That's all I know.

**Comment by AmoghDabholkar** [comment]
Thanks @deeox  for raising the issue. I was facing the same problem. However, I guess it's working now for both vggface2 as well as casia-webface (@x13machine )

**Comment by deeox** [comment]
Yeah, seems like it was fixed somehow. I'm closing the issue, Thanks @AmoghDabholkar

**Comment by purnasai** [comment]
Hi, I am still facing the same error. Could anyone tell me what made the code to run

**Comment by AmoghDabholkar** [comment]
Yup, just checked, the issue has somehow resurfaced again

**Comment by timesler** [comment]
@deeox @x13machine @AmoghDabholkar the model artifacts have now been moved to github in version 2.3.0, so this intermittant issue should hopefully be resolved.
